import { collectDefaultMetrics, Counter, Histogram, Registry } from 'prom-client';

export const registry = new Registry();
collectDefaultMetrics({ register: registry });

export const generatedTicks = new Counter({
  name: 'feeder_generated_ticks_total',
  help: 'Number of ticks generated by feeder',
  registers: [registry],
});
export const postAttempts = new Counter({
  name: 'feeder_post_attempts_total',
  help: 'Webhook post attempts labeled by status',
  labelNames: ['status'] as const,
  registers: [registry],
});
export const httpLatency = new Histogram({
  name: 'feeder_post_latency_seconds',
  help: 'Webhook post latency',
  buckets: [0.05, 0.1, 0.2, 0.5, 1, 2, 5],
  registers: [registry],
});